language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc

before_install:
- sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
- sudo apt-get update -qq

install:
- sudo apt-get -y install libgl1-mesa-dev qt510base ; fi
- source /opt/qt*/bin/qt*-env.sh

script:
- qmake ArchInstaller.pro -spec linux-g++ CONFIG+=release PREFIX=/usr
- make -j$(nproc)
- make
